#include "MFSGenerator.hpp"
#include "quick-cliques/src/TomitaAlgorithm.h"

using std::function;
using std::list;

MFSGenerator::MFSGenerator(const Graph<size_t>& graph,
			   function<bool(const list<int>&)> callback)
{
  /* Construct adjacency matrix of the graph */
  Vector<Vector<size_t>> vAdjacencyMatrix = graph.adjacencyMatrix();
  n = graph.size();

  adjacencyMatrix = (char**)calloc(n, sizeof(char*));

  for (int i = 0; i < n; i++)
  {
    adjacencyMatrix[i] = (char*)calloc(n, sizeof(char));

    for (int j = 0; j < n; j++)
      adjacencyMatrix[i][j] = vAdjacencyMatrix[i][j];
  }

  /* Initialize algorithm */
  pAlgorithm = new TomitaAlgorithm(adjacencyMatrix, n);
  pAlgorithm->AddCallBack(callback); //DF: this callback will be invoked once the MFS is generated by pAlgorithm
}

long MFSGenerator::run()
{
  list<list<int>> cliques;

  return pAlgorithm->Run(cliques);
}

MFSGenerator::~MFSGenerator()
{
  /* Free adjacency matrix */
  if (adjacencyMatrix != nullptr)
  {
    int i = 0;

    while (i < n)
    {
      free(adjacencyMatrix[i]);
      i++;
    }

    free(adjacencyMatrix);
  }

  /* Delete algorithm object */
  delete pAlgorithm;
}
